spring.application.name=SmartTaskPlannerWeb

spring.datasource.url=jdbc:sqlite:tasks.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-test-query=SELECT 1
